accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login
from . import views

urlpatterns = [
    url(r'^login/$', login, name='login', kwargs={'template_name': 'accounts/login.html'}),
    url(r'^profile/$', views.profile, name="profile"),
]

iamport/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.shortcuts import redirect
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^$', lambda r:redirect('shop:index'), name='root'),
    url(r'^accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.ItemListView.as_view(), name='index'),
    url(r'^(?P<item_id>\d+)/order/new/$', views.order_new, name='order_new')
]

accounts/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.conf import settings
from uuid import uuid4

class Item(models.Model):
    name = models.CharField(max_length = 100, verbose_name = '상품명')
    desc = models.TextField(blank = True)
    amount = models.PositiveIntegerField(verbose_name = '가격')
    photo = models.ImageField()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    item = models.ForeignKey(Item)
    merchant_uid = models.UUIDField(default=uuid4, editable=False)
    imp_uid = models.CharField(max_length=100, blank=True)
    name = models.CharField(max_length = 100, verbose_name = '상품명')
    amount = models.PositiveIntegerField(verbose_name = '결제금액')
    status = models.CharField(
        max_length=9,
        choices= (
            ('ready', '미결제'),
            ('paid', '결제완료'),
            ('cancelled', '결제취소'),
            ('failed', '결제실패'),
        ),
        default='ready',
        db_index=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

shop/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['name', 'amount']
        widgets = {
            'name': forms.TextInput(attrs = {'readonly': 'readonly'}),
            'amount': forms.TextInput(attrs = {'readonlu': 'readonly'}),
        }

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from shop.models import Order

@login_required
def profile(request):
    order_list = Order.objects.filter(user=request.user)
    return render(request, 'accounts/profile.html', {
        'order_list': order_list,
    })

shop/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Item, Order
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
from .forms import OrderForm

class ItemListView(ListView):
    model = Item

    def get_queryset(self):
        self.q = self.request.GET.get('q', '')

        qs = super().get_queryset()
        
        if self.q:
            qs = qs.filter(name__icontains=self.q)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['q'] = self.q
        return context


@login_required
def order_new(request, item_id):
    item = get_object_or_404(Item, pk = item_id)
    initial = {'name': item.name, "amount": item.amount}

    if request.method == 'POST':
        form = OrderForm(request.POST, initial = initial)
        if form.is_valid():
            order = form.save(commit = False)
            order.user = request.user
            order.item = item
            order.save()
            return redirect('profile')
    else:
        form = OrderForm(initial = initial)
    
    return render(request, 'shop/order_form.html', {
        'form': form,
        'iamport_shop_id': 'iamport',
    })

accounts/templates/accounts/login.html
{% extends "accounts/layout.html" %}

{% block content %}
    <div class="container">
        <div class="col-md-8 offset-md-2 mt-3">
            <form action="" method="post">
                {% csrf_token %}
                <div class="card card-default">
                    <div class="card-header">
                        회원가입
                    </div>
                    <div class="card-body">
                        <table>
                            {{ form.as_table }}
                        </table>
                    </div>
                    <div class="card-footer">
                        <input type="submit" class="btn btn-primary">
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "accounts/layout.html" %}
{% load humanize %}

{% block content %}
    <div class="container">
        <div class="col-md-12 mt-3">
            <h1>{{ user }}'s Profile</h1>

            <h3>주문내역</h3>

            <table class="table table-hover table-bordered">
                <thead>
                    <tr>
                        <th>상품명</th>
                        <th>결제가격</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in order_list %}
                        <tr>
                            <td>{{ order.name }}</td>
                            <td class="text-right">{{ order.amount }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

iamport/templates/layout.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <title>[AskDjango 특강] 아임포트 결제 연동</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/4.0.0-beta.2/cosmo/bootstrap.min.css" />
    <script src="//code.jquery.com/jquery-2.2.4.min.js"></script>
</head>
<body>
	<nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url "shop:index" %}">AskDjango 쇼핑몰</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarsExampleDefault">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link" href="{% url "shop:index" %}">Home</span></a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">Link</a>
				</li>
				<li class="nav-item">
					<a class="nav-link disabled" href="#">Disabled</a>
				</li>
			</ul>
			<form class="form-inline my-2 my-lg-0" action="{% url "shop:index" %}" method="get">
				<input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="q" value="{{ q }}" />
				<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
			</form>
		</div>
	</nav>

    {% block content %}
    {% endblock %}

    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
    {% block extra_body %}
    {% endblock %}
</body>
</html>

shop/templates/shop/index.html
<h1>Hi</h1>
<script src="//code.jquery.com/jquery-1.12.4.min.js" ></script>
<script src="//service.iamport.kr/js/iamport.payment-1.1.5.js"></script>
<script>
    (function() {
        var IMP = window.IMP;
        var code = "imp84502314"; // FIXME: 가맹점 식별코드
        IMP.init(code);

        // 결제요청
            IMP.request_pay({
            pay_method : 'card',
            merchant_uid : 'merchant_' + new Date().getTime(),
            name : '주문명:결제테스트',
            amount : 100,
            buyer_email : 'iamport@siot.do',
            buyer_name : '구매자이름',
            buyer_tel : '010-1234-5678',
            buyer_addr : '서울특별시 강남구 삼성동',
            buyer_postcode : '123-456',
            m_redirect_url : 'https://www.yourdomain.com/payments/complete'
        }, function(rsp) {
            if ( rsp.success ) {
                var msg = '결제가 완료되었습니다.';
                msg += '고유ID : ' + rsp.imp_uid;
                msg += '상점 거래ID : ' + rsp.merchant_uid;
                msg += '결제 금액 : ' + rsp.paid_amount;
                msg += '카드 승인번호 : ' + rsp.apply_num;
            }
            else {
                var msg = '결제에 실패하였습니다. 에러내용 : ' + rsp.error_msg
            }
            alert(msg);
        });
    })();
</script>

shop/templates/shop/item_list.html
{% extends "shop/layout.html" %}
{% load humanize %}

{% block content %}
    <div class="container">
        <div class="row">
            {% for item in item_list %}
                <div class="col-sm-3 mb-3">
                    <div class="card">
                        <img src="{{ item.photo.url }}" class="card-img-top" alt="">
                        <div class="card-body">
                            <p class="card-text" style="line-height: 1.5em; height: 3em; text-overflow: ellipsis;">{{ item.name }}</p>
                            <p class="card-text text-right">{{ item.amount|intcomma }}</p>
                        </div>
                        <a href="{% url "shop:order_new" item.pk %}" class="btn btn-primary btn-block">구매하기</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

shop/templates/shop/layout.html
{% extends "layout.html" %}

shop/templates/shop/order_form.html
{% extends "shop/layout.html" %}

{% block content %}
    <div class="container">
        <div class="col-md-8 offset-md-2 mt-3">
            <form action="" method="post" id="order-form">
                {% csrf_token %}
                <div class="card card-default">
                    <div class="card-header">
                        주문하기
                    </div>
                    <div class="card-body">
                        <table>
                            {{ form.as_table }}
                        </table>
                    </div>
                    <div class="card-footer">
                        <input type="submit" class="btn btn-primary" value = '결제하기'>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block extra_body %}
    <script src="https://service.iamport.kr/js/iamport.payment-1.1.5.js"></script>
    <script>
        $(function() {
            var $form = $('#order-form');
            var params = {
                name: $form.find('[name=name]').val(),
                amount: $form.find('[name=amount]').val(),
            };

            IMP.init('{{ iamport_shop_id }}');
            IMP.request_pay(params, function(response_data) {
                console.log('response_data : ', response_data);

                if(!response_data.success) {
                    alert(response_data.error_msg + "(" + response_data.error_code + ")");
                    location.href = '{% url "shop:index" %}';
                }
                else {
                    $.each(response_data, function(key, value) {
                        $form.find("input[name=" + key + "]").val(value);
                    });
                    $form.submit();
                }
            });
        });
    </script>
{% endblock %}